// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------------- //
// PIO_JTAG_SET_PIN_CONFIG //
// ----------------------- //

#define PIO_JTAG_SET_PIN_CONFIG_wrap_target 0
#define PIO_JTAG_SET_PIN_CONFIG_wrap 0

static const uint16_t PIO_JTAG_SET_PIN_CONFIG_program_instructions[] = {
            //     .wrap_target
    0xe08f, //  0: set    pindirs, 15                
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PIO_JTAG_SET_PIN_CONFIG_program = {
    .instructions = PIO_JTAG_SET_PIN_CONFIG_program_instructions,
    .length = 1,
    .origin = -1,
};

static inline pio_sm_config PIO_JTAG_SET_PIN_CONFIG_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PIO_JTAG_SET_PIN_CONFIG_wrap_target, offset + PIO_JTAG_SET_PIN_CONFIG_wrap);
    return c;
}
#endif

// ----------------------- //
// PIO_JTAG_SET_PIN_OUTPUT //
// ----------------------- //

#define PIO_JTAG_SET_PIN_OUTPUT_wrap_target 0
#define PIO_JTAG_SET_PIN_OUTPUT_wrap 0

static const uint16_t PIO_JTAG_SET_PIN_OUTPUT_program_instructions[] = {
            //     .wrap_target
    0xe00f, //  0: set    pins, 15                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PIO_JTAG_SET_PIN_OUTPUT_program = {
    .instructions = PIO_JTAG_SET_PIN_OUTPUT_program_instructions,
    .length = 1,
    .origin = -1,
};

static inline pio_sm_config PIO_JTAG_SET_PIN_OUTPUT_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PIO_JTAG_SET_PIN_OUTPUT_wrap_target, offset + PIO_JTAG_SET_PIN_OUTPUT_wrap);
    return c;
}
#endif

// -------- //
// PIO_JTAG //
// -------- //

#define PIO_JTAG_wrap_target 0
#define PIO_JTAG_wrap 8

#define PIO_JTAG_offset_PIO_JTAG_RESET 1u

static const uint16_t PIO_JTAG_program_instructions[] = {
            //     .wrap_target
    0xf824, //  0: set    x, 4            side 3     
    0xe901, //  1: set    pins, 1         side 1 [1] 
    0xf801, //  2: set    pins, 1         side 3     
    0x1841, //  3: jmp    x--, 1          side 3     
    0xbf42, //  4: nop                    side 3 [7] 
    0xbf42, //  5: nop                    side 3 [7] 
    0xbf42, //  6: nop                    side 3 [7] 
    0xbf42, //  7: nop                    side 3 [7] 
    0xbf42, //  8: nop                    side 3 [7] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PIO_JTAG_program = {
    .instructions = PIO_JTAG_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config PIO_JTAG_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PIO_JTAG_wrap_target, offset + PIO_JTAG_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

