// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------------- //
// PIO_JTAG_SET_PIN_CONFIG //
// ----------------------- //

#define PIO_JTAG_SET_PIN_CONFIG_wrap_target 0
#define PIO_JTAG_SET_PIN_CONFIG_wrap 0

static const uint16_t PIO_JTAG_SET_PIN_CONFIG_program_instructions[] = {
            //     .wrap_target
    0xe08f, //  0: set    pindirs, 15                
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PIO_JTAG_SET_PIN_CONFIG_program = {
    .instructions = PIO_JTAG_SET_PIN_CONFIG_program_instructions,
    .length = 1,
    .origin = -1,
};

static inline pio_sm_config PIO_JTAG_SET_PIN_CONFIG_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PIO_JTAG_SET_PIN_CONFIG_wrap_target, offset + PIO_JTAG_SET_PIN_CONFIG_wrap);
    return c;
}
#endif

// ----------------------- //
// PIO_JTAG_SET_PIN_OUTPUT //
// ----------------------- //

#define PIO_JTAG_SET_PIN_OUTPUT_wrap_target 0
#define PIO_JTAG_SET_PIN_OUTPUT_wrap 0

static const uint16_t PIO_JTAG_SET_PIN_OUTPUT_program_instructions[] = {
            //     .wrap_target
    0xe00f, //  0: set    pins, 15                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PIO_JTAG_SET_PIN_OUTPUT_program = {
    .instructions = PIO_JTAG_SET_PIN_OUTPUT_program_instructions,
    .length = 1,
    .origin = -1,
};

static inline pio_sm_config PIO_JTAG_SET_PIN_OUTPUT_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PIO_JTAG_SET_PIN_OUTPUT_wrap_target, offset + PIO_JTAG_SET_PIN_OUTPUT_wrap);
    return c;
}
#endif

// ----------------------- //
// PIO_JTAG_RESET_AND_IDLE //
// ----------------------- //

#define PIO_JTAG_RESET_AND_IDLE_wrap_target 0
#define PIO_JTAG_RESET_AND_IDLE_wrap 5

static const uint16_t PIO_JTAG_RESET_AND_IDLE_program_instructions[] = {
            //     .wrap_target
    0xfc24, //  0: set    x, 4            side 3     
    0xf501, //  1: set    pins, 1         side 1 [1] 
    0xfc01, //  2: set    pins, 1         side 3     
    0x0041, //  3: jmp    x--, 1                     
    0xf101, //  4: set    pins, 1         side 0 [1] 
    0xf901, //  5: set    pins, 1         side 2 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PIO_JTAG_RESET_AND_IDLE_program = {
    .instructions = PIO_JTAG_RESET_AND_IDLE_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config PIO_JTAG_RESET_AND_IDLE_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PIO_JTAG_RESET_AND_IDLE_wrap_target, offset + PIO_JTAG_RESET_AND_IDLE_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif

// -------- //
// PIO_JTAG //
// -------- //

#define PIO_JTAG_wrap_target 0
#define PIO_JTAG_wrap 27

static const uint16_t PIO_JTAG_program_instructions[] = {
            //     .wrap_target
    0xe041, //  0: set    y, 1                       
    0x6020, //  1: out    x, 32                      
    0x0036, //  2: jmp    !x, 22                     
    0xf501, //  3: set    pins, 1         side 1 [1] 
    0xfd01, //  4: set    pins, 1         side 3 [1] 
    0xf501, //  5: set    pins, 1         side 1 [1] 
    0xfd01, //  6: set    pins, 1         side 3 [1] 
    0xf101, //  7: set    pins, 1         side 0 [1] 
    0xf901, //  8: set    pins, 1         side 2 [1] 
    0xf101, //  9: set    pins, 1         side 0 [1] 
    0xf901, // 10: set    pins, 1         side 2 [1] 
    0x7201, // 11: out    pins, 1         side 0 [2] 
    0xb842, // 12: nop                    side 2     
    0x4001, // 13: in     pins, 1                    
    0x004b, // 14: jmp    x--, 11                    
    0x7601, // 15: out    pins, 1         side 1 [2] 
    0xbd42, // 16: nop                    side 3 [1] 
    0x4001, // 17: in     pins, 1                    
    0x8020, // 18: push   block                      
    0x0081, // 19: jmp    y--, 1                     
    0xf501, // 20: set    pins, 1         side 1 [1] 
    0x1d1a, // 21: jmp    26              side 3 [1] 
    0xfc24, // 22: set    x, 4            side 3     
    0xf501, // 23: set    pins, 1         side 1 [1] 
    0xbc42, // 24: nop                    side 3     
    0x0057, // 25: jmp    x--, 23                    
    0xb142, // 26: nop                    side 0 [1] 
    0xb942, // 27: nop                    side 2 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PIO_JTAG_program = {
    .instructions = PIO_JTAG_program_instructions,
    .length = 28,
    .origin = -1,
};

static inline pio_sm_config PIO_JTAG_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PIO_JTAG_wrap_target, offset + PIO_JTAG_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif

