// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// square //
// ------ //

#define square_wrap_target 1
#define square_wrap 2

static const uint16_t square_program_instructions[] = {
    0xe083, //  0: set    pindirs, 3                 
            //     .wrap_target
    0xe001, //  1: set    pins, 1                    
    0xe002, //  2: set    pins, 2                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program square_program = {
    .instructions = square_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config square_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + square_wrap_target, offset + square_wrap);
    return c;
}
#endif

