// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define PIO_SWD_TICK_PER_SWD_PERIOD 4

// ----------- //
// pio_swd_cmd //
// ----------- //

#define pio_swd_cmd_wrap_target 0
#define pio_swd_cmd_wrap 28

static const uint16_t pio_swd_cmd_program_instructions[] = {
            //     .wrap_target
    0xe083, //  0: set    pindirs, 3                 
    0x80a0, //  1: pull   block                      
    0xe047, //  2: set    y, 7                       
    0x7a01, //  3: out    pins, 1         side 1 [2] 
    0x1283, //  4: jmp    y--, 3          side 0 [2] 
    0xfc81, //  5: set    pindirs, 1      side 1 [4] 
    0xf442, //  6: set    y, 2            side 0 [4] 
    0x5a01, //  7: in     pins, 1         side 1 [2] 
    0x1287, //  8: jmp    y--, 7          side 0 [2] 
    0x8020, //  9: push   block                      
    0x80a0, // 10: pull   block                      
    0x6020, // 11: out    x, 32                      
    0x0035, // 12: jmp    !x, 21                     
    0xe05f, // 13: set    y, 31                      
    0x5a01, // 14: in     pins, 1         side 1 [2] 
    0x128e, // 15: jmp    y--, 14         side 0 [2] 
    0x8020, // 16: push   block                      
    0x5a01, // 17: in     pins, 1         side 1 [2] 
    0xb242, // 18: nop                    side 0 [2] 
    0x8020, // 19: push   block                      
    0x0000, // 20: jmp    0                          
    0xfa83, // 21: set    pindirs, 3      side 1 [2] 
    0x92a0, // 22: pull   block           side 0 [2] 
    0xe05f, // 23: set    y, 31                      
    0x7a01, // 24: out    pins, 1         side 1 [2] 
    0x1298, // 25: jmp    y--, 24         side 0 [2] 
    0x80a0, // 26: pull   block                      
    0x7a01, // 27: out    pins, 1         side 1 [2] 
    0xb242, // 28: nop                    side 0 [2] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_swd_cmd_program = {
    .instructions = pio_swd_cmd_program_instructions,
    .length = 29,
    .origin = -1,
};

static inline pio_sm_config pio_swd_cmd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_swd_cmd_wrap_target, offset + pio_swd_cmd_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ------------- //
// pio_swd_reset //
// ------------- //

#define pio_swd_reset_wrap_target 0
#define pio_swd_reset_wrap 31

static const uint16_t pio_swd_reset_program_instructions[] = {
            //     .wrap_target
    0xe083, //  0: set    pindirs, 3                 
    0x91a0, //  1: pull   block           side 0 [1] 
    0xf941, //  2: set    y, 1            side 1 [1] 
    0xe03f, //  3: set    x, 31                      
    0xe103, //  4: set    pins, 3                [1] 
    0x1144, //  5: jmp    x--, 4          side 0 [1] 
    0xe03f, //  6: set    x, 31                      
    0xe103, //  7: set    pins, 3                [1] 
    0x1147, //  8: jmp    x--, 7          side 0 [1] 
    0x00fc, //  9: jmp    !osre, 28                  
    0x0083, // 10: jmp    y--, 3                     
    0x80a0, // 11: pull   block                      
    0xe127, // 12: set    x, 7                   [1] 
    0x7201, // 13: out    pins, 1         side 0 [2] 
    0x1b4d, // 14: jmp    x--, 13         side 1 [3] 
    0xb142, // 15: nop                    side 0 [1] 
    0xe381, // 16: set    pindirs, 1             [3] 
    0xfc22, // 17: set    x, 2            side 1 [4] 
    0x5201, // 18: in     pins, 1         side 0 [2] 
    0x1b52, // 19: jmp    x--, 18         side 1 [3] 
    0x8020, // 20: push   block                      
    0xe13f, // 21: set    x, 31                  [1] 
    0x5201, // 22: in     pins, 1         side 0 [2] 
    0x1b56, // 23: jmp    x--, 22         side 1 [3] 
    0x8020, // 24: push   block                      
    0x5201, // 25: in     pins, 1         side 0 [2] 
    0x9a20, // 26: push   block           side 1 [2] 
    0x0000, // 27: jmp    0                          
    0xe02f, // 28: set    x, 15                      
    0x7101, // 29: out    pins, 1         side 0 [1] 
    0x195d, // 30: jmp    x--, 29         side 1 [1] 
    0x000a, // 31: jmp    10                         
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_swd_reset_program = {
    .instructions = pio_swd_reset_program_instructions,
    .length = 32,
    .origin = -1,
};

static inline pio_sm_config pio_swd_reset_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_swd_reset_wrap_target, offset + pio_swd_reset_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

