// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define PIO_SWD_TICK_PER_SWD_PERIOD 4

// ----------- //
// pio_swd_cmd //
// ----------- //

#define pio_swd_cmd_wrap_target 0
#define pio_swd_cmd_wrap 31

static const uint16_t pio_swd_cmd_program_instructions[] = {
            //     .wrap_target
    0xf083, //  0: set    pindirs, 3      side 0     
    0x90a0, //  1: pull   block           side 0     
    0xe047, //  2: set    y, 7                       
    0x7201, //  3: out    pins, 1         side 0 [2] 
    0x1a83, //  4: jmp    y--, 3          side 1 [2] 
    0xf281, //  5: set    pindirs, 1      side 0 [2] 
    0xfa42, //  6: set    y, 2            side 1 [2] 
    0x5201, //  7: in     pins, 1         side 0 [2] 
    0x1a87, //  8: jmp    y--, 7          side 1 [2] 
    0x8020, //  9: push   block                      
    0x80a0, // 10: pull   block                      
    0x6020, // 11: out    x, 32                      
    0x0035, // 12: jmp    !x, 21                     
    0xe05f, // 13: set    y, 31                      
    0x5201, // 14: in     pins, 1         side 0 [2] 
    0x1a8e, // 15: jmp    y--, 14         side 1 [2] 
    0x8020, // 16: push   block                      
    0x5201, // 17: in     pins, 1         side 0 [2] 
    0xba42, // 18: nop                    side 1 [2] 
    0x8020, // 19: push   block                      
    0x001c, // 20: jmp    28                         
    0xf283, // 21: set    pindirs, 3      side 0 [2] 
    0x9aa0, // 22: pull   block           side 1 [2] 
    0xe05f, // 23: set    y, 31                      
    0x7201, // 24: out    pins, 1         side 0 [2] 
    0x1a98, // 25: jmp    y--, 24         side 1 [2] 
    0x80a0, // 26: pull   block                      
    0x7201, // 27: out    pins, 1         side 0 [2] 
    0xfa29, // 28: set    x, 9            side 1 [2] 
    0xf183, // 29: set    pindirs, 3      side 0 [1] 
    0xf900, // 30: set    pins, 0         side 1 [1] 
    0x115e, // 31: jmp    x--, 30         side 0 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_swd_cmd_program = {
    .instructions = pio_swd_cmd_program_instructions,
    .length = 32,
    .origin = -1,
};

static inline pio_sm_config pio_swd_cmd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_swd_cmd_wrap_target, offset + pio_swd_cmd_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ------------- //
// pio_swd_reset //
// ------------- //

#define pio_swd_reset_wrap_target 0
#define pio_swd_reset_wrap 31

static const uint16_t pio_swd_reset_program_instructions[] = {
            //     .wrap_target
    0xf083, //  0: set    pindirs, 3      side 0     
    0x90a0, //  1: pull   block           side 0     
    0xe041, //  2: set    y, 1                       
    0xe03f, //  3: set    x, 31                      
    0xe102, //  4: set    pins, 2                [1] 
    0x1944, //  5: jmp    x--, 4          side 1 [1] 
    0xe03f, //  6: set    x, 31                      
    0xe102, //  7: set    pins, 2                [1] 
    0x1947, //  8: jmp    x--, 7          side 1 [1] 
    0x00fc, //  9: jmp    !osre, 28                  
    0x0083, // 10: jmp    y--, 3                     
    0x80a0, // 11: pull   block                      
    0xe027, // 12: set    x, 7                       
    0x7101, // 13: out    pins, 1         side 0 [1] 
    0x194d, // 14: jmp    x--, 13         side 1 [1] 
    0xf181, // 15: set    pindirs, 1      side 0 [1] 
    0xf922, // 16: set    x, 2            side 1 [1] 
    0x5101, // 17: in     pins, 1         side 0 [1] 
    0x1951, // 18: jmp    x--, 17         side 1 [1] 
    0xe13f, // 19: set    x, 31                  [1] 
    0x5101, // 20: in     pins, 1         side 0 [1] 
    0x1954, // 21: jmp    x--, 20         side 1 [1] 
    0xf12a, // 22: set    x, 10           side 0 [1] 
    0xb942, // 23: nop                    side 1 [1] 
    0xf183, // 24: set    pindirs, 3      side 0 [1] 
    0xf900, // 25: set    pins, 0         side 1 [1] 
    0x1159, // 26: jmp    x--, 25         side 0 [1] 
    0x1100, // 27: jmp    0               side 0 [1] 
    0xe02f, // 28: set    x, 15                      
    0x7101, // 29: out    pins, 1         side 0 [1] 
    0x195d, // 30: jmp    x--, 29         side 1 [1] 
    0x000a, // 31: jmp    10                         
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_swd_reset_program = {
    .instructions = pio_swd_reset_program_instructions,
    .length = 32,
    .origin = -1,
};

static inline pio_sm_config pio_swd_reset_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_swd_reset_wrap_target, offset + pio_swd_reset_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

